website_hassan/shop/urls.py
from . import views
from django.urls import path

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('base/', views.base, name='base'),
    path('store/', views.store, name='store'),
    path('product/<int:pk>/', views.product, name='product'),

]

website_hassan/website_hassan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website_hassan/shop/models.py
from audioop import reverse
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class logo(models.Model):
    name = models.CharField(max_length=50)
    create_time: datetime = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/base/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('create_time',)

    def __str__(self):
        return self.name


class drbare_ma(models.Model):
    name = models.CharField(max_length=50)
    namber = models.CharField(max_length=12)
    n_email = models.CharField(max_length=100)
    n_insta = models.CharField(max_length=100)
    addres = models.CharField(max_length=100)
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('create_time',)

    def __str__(self):
        return self.name


class hspio(models.Model):
    name = models.CharField(max_length=50)
    n_h2 = models.CharField(max_length=50)
    n_span = models.CharField(max_length=100)
    n_p = models.CharField(max_length=300)
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('create_time',)

    def __str__(self):
        return self.name


class hspia(models.Model):
    name = models.CharField(max_length=50)
    n_h2 = models.CharField(max_length=50)
    n_span = models.CharField(max_length=100)
    n_p = models.CharField(max_length=1000)
    image = models.ImageField(upload_to='images/index/%Y/%m/%d', blank=True)
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=10, decimal_places=0, default=None)


    class Meta:
        ordering = ('create_time',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product', args=[self.id])

website_hassan/shop/views.py
from django.shortcuts import render, get_object_or_404
from . import models


def base(request):
    base_list = models.logo.objects.all()
    base_list1 = models.drbare_ma.objects.all()
    return render(request, 'base.html', {'base_list': base_list,
                                         'base_list1': base_list1})


def index(request):
    index_listo = models.hspio.objects.all()[:3]
    product_list = models.hspia.objects.all()
    base_list = models.logo.objects.all()
    base_list1 = models.drbare_ma.objects.all()
    return render(request, 'index.html', {'index_listo': index_listo,
                                          'product_list': product_list,
                                          'base_list': base_list,
                                          'base_list1': base_list1})


def store(request):
    store_list = models.hspia.objects.all()
    base_list = models.logo.objects.all()
    base_list1 = models.drbare_ma.objects.all()
    return render(request, 'store.html', {'store_list': store_list,
                                          'base_list': base_list,
                                          'base_list1': base_list1})


def product(request, pk):
    base_list = models.logo.objects.all()
    base_list1 = models.drbare_ma.objects.all()
    product_d = get_object_or_404(models.hspia, id=pk)
    return render(request, 'product.html', {'product_d': product_d,
                                            'base_list': base_list,
                                            'base_list1': base_list1})

website_hassan/shop/templates/base.html
<!DOCTYPE html>
{% load static %}

<html dir="rtl" lang="fr">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-v4-rtl/4.5.2-1/css/bootstrap.min.css"
          integrity="sha512-Nts+3M9snzcMkpLFNQ2sesyPc/EkWWVdJZMQaJeQMx6OoVs1kWNEFRG464CdIfyB9gjgKbDMFovNQxfTs40+8g=="
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-v4-rtl/4.5.2-1/css/bootstrap-grid.min.css"
          integrity="sha512-RYWaVFBqTu5V7SMDzGHTyqFsno+luBDh9x69Tpu//J3pgBsJl5zeCkEDdD/4RUpF0GT25i8vUHJeCIujE4bj0A=="
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-v4-rtl/4.5.2-1/css/bootstrap-rtl.min.css"
          integrity="sha512-+1C9xBCl0azgGjU6bIsATfB4XOQ0MSFduPs388NiyzwYt4nfelS72KSPSFZT338FjP7F3mMme2re8+gUJe2HZQ=="
          crossorigin="anonymous"/>

</head>
<body style="background: #fffaf4">
<header class="header ff">
     <div class="row">
         <div class="col">
    <nav class="navbar navbar-expand-lg navbar-light "style="background: #00163d">

        <div class="collapse navbar-collapse "  id="navbarNavAltMarkup">
            <div class="navbar-nav " >
                <a class="nav-item nav-link active "style="color: #9d9d9d " href="{% url 'shop:index' %}">خانه <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link "style="color: #9d9d9d " href="{% url 'shop:store' %}" >فروشگاه</a>
                <a class="nav-item nav-link" style="color: #9d9d9d " href="{% url 'shop:base' %}">درباره ما</a>
            </div>
        </div>
            {% for i in base_list %}
                    <a class="navbar-brand" href="{% url 'shop:index' %}">
                        <img src="{{ i.image.url }}" width="30" height="30" class="d-inline-block align-top" alt="{{ i.name }}">
                    </a>
            {% endfor %}
        <button class="navbar-toggler" style="background: #9d9d9d" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
         </div>
     </div>

</header>

{% block content %}

{% endblock %}
        <footer class="footer ff pt-4 my-md-5 pt-md-5 border-top navbar-light " style="background: #00163d">

            <div class="row">

                <div class="col-6 col-md rtl align-top">
                    <h5 style="color: #9d9d9d">درباره ما</h5>
                    <ul class="list-unstyled text-small">
                        {% for j in base_list1 %}

                            <li><a style="color: white" href="#">{{ j.name }}</a></li>
                            <li><a style="color: white" href="#">{{ j.namber }}</a></li>
                            <li><a style="color: white" href="#">{{ j.n_email }}</a></li>
                            <li><a style="color: white" href="#">{{ j.n_insta }}</a></li>
                            <li><a style="color: white" href="#">{{ j.addres }}</a></li>
                            </ul>
                        {% endfor %}
                </div>
                <div class="col-12 col-md ">
                    {% for i in base_list %}
                    <img class="mb-2" src="{{ i.image.url }}" alt="" width="24" height="24">
                    {% endfor %}
                    <small class="d-block mb-3 " style="color: white "> 1398-1399</small>
                </div>
            </div>
    </footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"
        integrity="sha512-/DXTXr6nQodMUiq+IUJYCt2PPOUjrHJ9wFrqpJ3XkgPNOZVfMok7cRw6CSxyCQxXn6ozlESsSh1/sMCTF1rL/g=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.4/umd/popper.min.js"
        integrity="sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-v4-rtl/4.5.2-1/js/bootstrap.min.js"
        integrity="sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-v4-rtl/4.5.2-1/js/bootstrap.bundle.min.js"
        integrity="sha512-kBFfSXuTKZcABVouRYGnUo35KKa1FBrYgwG4PAx7Z2Heroknm0ca2Fm2TosdrrI356EDHMW383S3ISrwKcVPUw=="
        crossorigin="anonymous"></script>
{#<script>#}
{#    $("li a:odd").css("color", "#000000");#}
{#    $("li a:even").css("color", "gold");#}
{#</script>#}
</body>
</html>

website_hassan/shop/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} خانه {% endblock %}
{% block content %}

    <div class="jumbotron ff text-center" style="background: #e5d6b7 ">
        <div>
            <div class="container">
                <h1 class="display-3" style="color: #4c4731">عسل 100% طبیعی</h1>
                <p>

                </p>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row">
            {% for i in index_listo %}
                <div class="col-md-4 rtl ff ">
                    <h2>{{ i.n_h2 }}</h2>
                    <p>
                        {{ i.n_p }}
                    </p>
                    <p><a class="btn btn-secondary" href="#" role="button">{{ i.n_span }} &raquo;</a></p>
                </div>
            {% endfor %}
        </div>
    </div>






    <div class="container ff">
        <div class="card border-0 shadow my-5">
            <div class="card-body p-5">
                <div class="row">
                    {% for i in product_list %}
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <div class="card flex-md-row mb-4 box-shadow h-md-250">
                                    <div class="card-body d-flex flex-column align-items-start">
                                        <h2 class="mb-0">
                                            <a class="text-dark" href="#">{{ i.n_h2 }}</a>
                                        </h2>
                                        <div class="mb-1 text-muted">{{ i.n_span }}</div>

                                        <h3 class="product-name"><a href="{{ i.get_absolute_url }}">بیشتر..</a></h3>
                                    </div>
                                    <div class="col-md-4">
                                        <img
                                                src="{{ i.image.url }}" style="height: 100%;width: 100%"
                                                alt="Card image cap">
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>



{% endblock %}

website_hassan/shop/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %} محصول {% endblock %}
{% block content %}

    <div class="container ff">
        <div class="card border-0 shadow my-5">
            <div class="card-body p-5">
                <div class="row">
                    <div class="row mb-2">
                        <div class="col-md-12">
                            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                                <div class="col-md-4">
                                    <img src="{{ product_d.image.url }}" style="height: 100%;width: 100%">
                                </div>
                                <div class="card-body d-flex flex-column align-items-start rtl">
                                    <h2 class="mb-0">
                                        <a class="text-dark" href="#">{{ product_d.n_h2 }}</a>
                                    </h2>
                                    <div class="mb-1 text-muted">{{ product_d.n_span }}</div>

                                    <p>{{ product_d.n_p }}</p>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

website_hassan/shop/templates/store.html
{% extends 'base.html' %}
{% load static %}
{% block title %} فروشگاه {% endblock %}
{% block content %}

    <div class="alert alert-success ff rtl">
        <strong>بخش خرید در حال تکمیل است .</strong> از صبوری شما متشکریم.
    </div>
    <div class="alert alert-primary ff rtl">
        <strong><a href="{% url 'shop:base' %}">می توانید در صورت نیاز از با ما تماس بگیرید .</a>  </strong>
    </div>
    <div class="album py-5 ">
        <div class=" rtl">
            <div class="container">
                <div class="row">
                    {% for i in store_list %}
                        <div class="col-md-4 ">
                            <div class="card mb-4 box-shadow ">
                                <div class="card-header ">
                                    <h4 class="my-0 font-weight-normal">{{ i.name }}</h4>
                                </div>
                                <div class="product">
                                    <div class="product-img">
                                        <img class="img-thumbnail img-responsive "
                                             src="{{ i.image.url }}" style="height: 262pt">
                                    </div>
                                    <div class="card-body">
                                        <h1 class="card-title pricing-card-title">{{ i.price }} <small
                                                class="text-muted">تومان</small></h1>

                                        <button id="p1" type="button "
                                                class="btn btn-lg btn-block btn-outline-warning">
                                            خرید
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}